Updated texts in txm project.
mild-blue/about pull request #103
Opened 2022-03-29 15:32 UTC by bielovico

I wanted to update texts for our txm landing page to better reflect their target audience of doctors and researchers.

2022-03-29 19:24 UTC, tomaskourim requested changes

2022-03-29 19:24 UTC, tomaskourim commented on projects/txm.json
> +  "subtitle_cs": "Nástroj pro optimalizaci a manažment párové výměny ledvin.",
manažment je divné slovo. Dal bych správu.

2022-03-29 19:24 UTC, tomaskourim commented on projects/txm.json
> +    "TX Matching je nástroj, který umožňuje párovou výměnu zorganizovat a najít v rámci ní optimální kombinaci dárců a příjemců. Organizátor párové výměny využije na její manažment kontrolu uživatels
kombinaci dárců a příjemců. Pro správu párové výměny nabízí pohodlnou kontrolu přístupu uživatelů, automatické ....

2022-03-29 19:24 UTC, tomaskourim commented on projects/txm.json
> +    "TX Matching je nástroj, který umožňuje párovou výměnu zorganizovat a najít v rámci ní optimální kombinaci dárců a příjemců. Organizátor párové výměny využije na její manažment kontrolu uživatels
Optimalizační algoritmus dokáže pracovat s celou řadou nastavitelných parametrů a díky tomu umožňuje maximální flexibilitu při hledání těch nejvhodnějších dárců.

2022-03-29 19:24 UTC, tomaskourim commented on projects/txm.json
> +    "Algoritmus TX Matchingu je postaven na otevřeném kódu a jeho aktuální verze je vždy přístupna k využití zdarma. Aktuálně je program TX Matching aktivně využíván pražským IKEM na manažment a opti
na open source kódu (je to dostatečně česky, bohužel) a celá platforma je volně dostupná odborné i laické veřejnosti... IKEM na správu a optimalizaci...

2022-03-29 19:24 UTC, tomaskourim commented on projects/txm.json
> +      "description_cs": "Flexibilní uživatelské prostředí umožnuje měnit priority a omezení výpočtu.",
umožňuje maximální flexibilitu díky velkému množství nastavitelných parametrů-

2022-03-30 12:42 UTC, bielovico commented on projects/txm.json
> +    "Algoritmus TX Matchingu je postaven na otevřeném kódu a jeho aktuální verze je vždy přístupna k využití zdarma. Aktuálně je program TX Matching aktivně využíván pražským IKEM na manažment a opti
laické veřejnosit?

2022-04-07 08:58 UTC, kubantjan commented
@tomaskourim mrkni at se to dothane

2022-06-02 08:02 UTC, bielovico commented
@tomaskourim pozrel som Tvoj commit, so vsetkym suhlasim, prosim approve a merge.

2022-06-02 08:35 UTC, tomaskourim approved these changes

2022-06-02 08:35 UTC, merged