Jana urbankova
mild-blue/about pull request #107
Opened 2022-04-07 14:32 UTC by JanaUrbankova

2022-04-10 19:53 UTC, tomaskourim requested changes

2022-04-10 19:53 UTC, tomaskourim commented on people/jana
> +  "short_desc_en": "Jana is part of our back office team. Her main strengths are organization, order and problem solving. She is at home in the IT industry thanks to his many years of experience in t
```suggestion
  "short_desc_en": "Jana is part of our back office team. She helps us stay organised, focused and up to date. Thanks to her previous experience in companies focusing on software development and robotics she feels in the IT sector and in Mild Blue like at home.",
```

2022-04-11 10:16 UTC, LukasForst commented
soubor se musi jmenovat "jana.json" nikoliv jenom "jana"

2022-04-11 10:28 UTC, JanaUrbankova commented
> soubor se musi jmenovat "jana.json" nikoliv jenom "jana"

A musím ho vytvořit znovu a nebo jde přejmenovat, prosím?

2022-04-11 10:46 UTC, LukasForst commented
Určitě jde přejmenovat 👍

2022-04-11 10:52 UTC, JanaUrbankova commented
> Určitě jde přejmenovat 👍

Hotovo.

2022-04-13 09:14 UTC, kubantjan commented
Jeste bude potreba nemecke verze textu, ale to by idealne mel doplnit @tomaskourim  

a pak prosimte ten format obrazku musi byt webp (da se pouzit treba https://convertio.co/png-webp/)

2022-04-13 09:15 UTC, kubantjan requested changes
za me dobre, jen ten format obrazku co pisu vyse a to ze tomas musi doplnit nemcinu

2022-04-13 14:23 UTC, JanaUrbankova commented
Obrázek už je snad dobře. A němčinu opravdu neovládám, takže prosím Tomáše, jestli vytvoří. Děkuji.

2022-04-14 09:25 UTC, kubantjan requested changes

2022-04-14 09:25 UTC, kubantjan commented on people/jana.json
> +  "name": “Jana Urbánková",
jeste bacha, jaky uvozovky pouzivas, jsou ruzny typy a ty tady pouzivas “ a taky " jenze vsude je potreba pouzivat jen "

2022-04-20 08:35 UTC, kubantjan approved these changes

2022-04-20 09:03 UTC, tomaskourim approved these changes

2022-04-20 09:03 UTC, merged