Create Eliška
mild-blue/about pull request #115
Opened 2022-05-10 08:59 UTC by MildBlueServiceAccount

2022-05-11 07:46 UTC, tomaskourim requested changes

2022-05-11 07:46 UTC, tomaskourim commented on people/Eliška.json
> +  "short_desc_en": "Eliška holds a Master's degree in Landscape Engineering. She has various experience from corporate sector  IT and banking. She is the person who ensures	the smooth running of the
a taky ty dvojite mezery si prosim oprav

2022-05-11 07:46 UTC, tomaskourim commented on people/Eliška.json
> +  "short_desc_de": "Eliška hat einen Abschluss als Ingenieur im Landschaftsbau. Sie verfügt über verschiedene Berufserfahrung Körperschaften in Umfeldern wie IT und Bankwesen. In Mild Blue sie ist ve
Eliška hat einen Abschluss als Ingenieur im Landschaftsbau. Sie verfügt über verschiedene Berufserfahrungen von Körperschaften in Umfeldern wie IT oder Bankwesen. In Mild Blue ist sie für einen reibungslosen Betrieb und Innovation im Bereich Backoffice und Geschäftsprozesse verantwortlich.

2022-05-11 07:46 UTC, tomaskourim commented on people/Eliška.json
> +  "short_desc_cs": "Eliška to od vystudovaného oboru “krajinné inženýrství”  do Mild Blue vzala oklikou přes IT a bankovní korporace. Má zkušenosti z oblasti analýzy, inovace i správy aplikací a proc
zas dvojite mezery podle me

2022-05-12 09:01 UTC, MildBlueServiceAccount commented on people/Eliška.json
> +  "short_desc_cs": "Eliška to od vystudovaného oboru “krajinné inženýrství”  do Mild Blue vzala oklikou přes IT a bankovní korporace. Má zkušenosti z oblasti analýzy, inovace i správy aplikací a proc
opraveno.

2022-05-12 10:18 UTC, kubantjan requested changes
maly koment

2022-05-12 10:18 UTC, kubantjan commented on people/Eliška.json
> +  "short_desc_en": "Eliška holds a Master's degree in Landscape Engineering. She has various experience from IT and banking corporate. She is the person who ensures the smooth running of Mild Blue´s
neni to corporation? 

a mozna from IT and banking corporations by to melo byt?

2022-05-12 10:26 UTC, merged