Christine suggestions.
mild-blue/about pull request #134
Opened 2022-08-04 15:22 UTC by tomaskourim

2022-08-05 06:33 UTC, kubantjan requested changes
Za me tohleto neni ted vubec priorita, protoze to ted predelavame celkem zasadne v ramci hodnot vize a mise. Ale cenim suggestions, budeme vedet od koho si zadat pak feedback na ty novy texty.. 

Takze jako klidne provedme update, nejsem proti, ale brzy snad zas tyhle texty zmizi.

2022-08-08 07:32 UTC, bielovico approved these changes
Súhlasím s Honzom s tým, že by sa snáď tie texty mohli čoskoro zmeniť, ale tým, že toto sú fakt kozmetické úpravy a zjavne k lepšiemu, určite by som mergoval.

2022-08-17 06:24 UTC, kubantjan approved these changes

2022-08-17 06:34 UTC, kubantjan commented
Zaviram tohleto, udelal jsem rebase, bylo tam desne konfliktu a udelal novy PR

2022-08-17 06:34 UTC, closed without merging