Create matej.json
mild-blue/about pull request #137
Opened 2022-08-22 20:14 UTC by matejkloucek

2022-09-15 12:34 UTC, tomaskourim requested changes

2022-09-15 12:34 UTC, tomaskourim commented on people/matej.json
> +  "short_desc_cs": "Matěj studuje Matematickou informatiku na Fakultě jaderné a fyzikálně inženýrské na ČVUT. V Mild Blue pracuje na pozici junior developer"
mohl bys treba rozvest, ze se zajimas o [optimalizaci, teorii grafu, neco takoveho], pripadne klidne i nejake konicky atd.

2022-09-19 18:51 UTC, MildBlueServiceAccount reviewed
oprav si prosím překlep v angličtině _optimalizazion_

2022-09-20 08:51 UTC, tomaskourim requested changes

2022-09-20 08:51 UTC, tomaskourim commented on people/matej.json
> +  "short_desc_en": "Matěj studies Mathematical Informatics at the Faculty of Nuclear Sciences and Physical Engineering at CTU. At Mild Blue, he works as a junior developer. His interests include grap
In his spare time Matěj loves to listen to music, travel or just hang around with friends.

->

When he is not working or studying, Matěj loves listening to good music, travelling or just hanging out with friends.

2022-09-22 18:14 UTC, closed without merging