Create anhelina.json
mild-blue/about pull request #139
Opened 2022-09-08 10:16 UTC by anhelina-sadovnikova

2022-09-15 12:37 UTC, tomaskourim requested changes

2022-09-15 12:37 UTC, tomaskourim commented on people/anhelina.json
> +  "short_desc_cs": "Anhelina je studentkou Fakulty biomedicínského inženýrství ČVUT, oboru Informatika a kybernetika ve zdravotnictví. Pracuje v Mild Blue jako frontend vývojářka."
mohla bys to take trochu rozvest. Treba napsat odkud jsi, co te zajima, co delas, ceho chces v Mild Blue (nebo v zivote) dosahnout atd. At je to trochu osobni, to pusobi dobre

2022-09-25 16:53 UTC, tomaskourim requested changes

2022-09-25 16:53 UTC, tomaskourim commented on people/sources.json
> -]
no ale tohle kdyz smazes, tak to nebude platny JSON. Jestli (spravne) pouzivas IDEA, tak by ti to melo rvat. Koukni.

2022-09-25 16:53 UTC, tomaskourim commented on people/anhelina.json
> +
ja osobne formatuju json bez tech mezer mezitim. A jestli nemas nejaky padny argument proc je tam mit, tak by je vynechal ;)

2022-09-25 16:53 UTC, tomaskourim commented on people/anhelina.json
> +  "nick": "Anhelina",
podle me jsi v USA rikala, ze se ti ma rikat nejak jinak, ne? Lina?

2022-09-27 11:10 UTC, anhelina-sadovnikova commented on people/anhelina.json
> +  "nick": "Anhelina",
Používám obě varianty, ale na Anhelinu jsem víc zvyklá :)

2022-09-27 14:36 UTC, tomaskourim approved these changes

2022-09-27 14:36 UTC, merged