Create zuzana.json
mild-blue/about pull request #141
Opened 2022-09-19 12:17 UTC by nazuzunana

2022-09-19 12:41 UTC, tomaskourim requested changes

2022-09-19 12:41 UTC, tomaskourim commented on people/zuzana.json
> +  "name": "Zuzana Červínová",
nemame tady nahodou mit i titul?

2022-09-19 12:41 UTC, tomaskourim commented on people/zuzana.json
> +  "short_desc_cs": "Zuzana je bakalář umění a absolvent kurzu Digitální akademie: Web v Czechitas. Ve společnosti Mild Blue pracuje jako junior frontend developer."
a nechces to trochu rozvest? Treba neco jako.
Zuzana vystudovala to a to, ale po case zjistila, ze ji vlastne bavi programovat a delat hezke weby. Tak se prihlasila do kurzu, naucila se spoustu veci (takovych a makovych) a ted prichazi cas pretavit teorii v praxi. 
Jakoze mi prijde fajn, kdyz jsou ty medailonky takove vic osobni

2022-09-19 14:49 UTC, kubantjan requested changes

2022-09-19 14:49 UTC, kubantjan commented on people/zuzana.json
> +  ",
nemuzes mit uvozkovky na zacatku radku v jsonu. takhle je to nevalidni (i github ti to zabarvuje cervene  )

2022-09-19 14:50 UTC, kubantjan commented
Fix jsonu, jinak ok

2022-09-20 08:57 UTC, tomaskourim submitted a review, later dismissed

2022-09-20 08:57 UTC, tomaskourim commented on people/zuzana.json
> +{
jeste se musis pridat do people.json

2022-09-20 08:57 UTC, tomaskourim commented on people/zuzana.json
> +  "short_desc_en": "Zuzana is a Bachelor of Arts and a graduate of the Czechitas Digital Academy: Web. The skills she gained during the course, as well as her artistic sense, Zuzana now uses at Mild
Jenom AJ grammar
The skills she gained during the course, as well as her artistic sense, Zuzana now uses at Mild Blue, where she works as a junior frontend developer.

->

She now uses the skills gained during the course as well as her artistic sense at Mild Blue, where she works as a junior frontend developer.

2022-09-20 14:54 UTC, kubantjan requested changes
Jeste prosim rebase nad master (nekdo uz tam neco mergnul pred tebou) (kdybys s gitem a rebasem bojovala, dej vedet) 

Jinak za me vypada dobre. 

jeste zminim ze good practice je vzdy kdyz dotahnes a cekas na review od nekoho tak dat re-request review aby ho to pinglo (ja jsem re-request ted nemel :)

2022-09-21 08:52 UTC, kubantjan approved these changes

2022-09-21 08:53 UTC, kubantjan approved these changes

2022-09-21 08:55 UTC, merged