Introduce Tomas
mild-blue/about pull request #19
Opened 2021-02-08 15:29 UTC by tomaspavlin

Trochu jsem zápasil s tím, co o sobě napsat, tak budu rád za zpětnou vazbu.

2021-02-09 10:03 UTC, tomaskourim approved these changes

2021-02-09 10:04 UTC, tomaskourim requested changes
Vlastne jeste jedna vec. Fotku bys mel nejak taky pridat. Magda ji pry už má připravenou

2021-02-09 10:22 UTC, MildBlueServiceAccount commented on people/tomasp.json
> +  "short_desc_en": "Tomas holds a Master's degree in artificial intelligence and he has many years of experience building applications that use machine learning approaches. While Tomas is skilled wit
myslím, žes to napsal hezky. 
Tenhle koment je tady, jen abych zjistila, jak se to dělá :-)
Magda

2021-02-09 12:18 UTC, tomaspavlin commented
> Vlastne jeste jedna vec. Fotku bys mel nejak taky pridat. Magda ji pry už má připravenou

Fotka je přidaná people/photos/tomasp.webp

2021-02-09 22:43 UTC, tomaskourim submitted a review, later dismissed

2021-02-10 13:45 UTC, kubantjan approved these changes

2021-02-10 19:14 UTC, merged