Pridani magdy
mild-blue/about pull request #20
Opened 2021-02-09 10:33 UTC by MildBlueServiceAccount

přidání medailonku na web. Fotku vyřeším s Nasťou.

2021-02-09 10:36 UTC, kubantjan requested changes
jeste je potreba pridat do sources.json jmeno magda :)

2021-02-09 10:42 UTC, kubantjan requested changes
Az pridas fotku, je to uz vse ok a muzeme mergovat :)

2021-02-09 12:21 UTC, misslecter commented on people/magda.json
> +"name": "Ing. Magda Císařová",
chybí jeste `key`:
```
"key": "magda",
```

Ten se pak použije jako název obrázku ve formátu `.webp`. Tedy se ještě musí nahrát soubor `magda.webp` do složky  `/people/photos `.

2021-02-09 13:44 UTC, misslecter commented on people/magda.json
> +"key":"magda"
jeste prosim pridat carku na konci radku ;)

2021-02-09 13:48 UTC, tomaskourim submitted a review, later dismissed
Pekny, pridej carku podle @misslecter a je to

2021-02-10 13:45 UTC, kubantjan approved these changes

2021-02-10 22:49 UTC, kubantjan approved these changes

2021-02-11 08:36 UTC, merged