update slp.blue based on feedback
mild-blue/about pull request #207
Opened 2023-04-12 09:01 UTC by bielovico

Updated slp.blue based on latest feedback

2023-04-13 08:35 UTC, tomaskourim requested changes

2023-04-13 08:35 UTC, tomaskourim commented on projects/slp.blue.json
> +      "description_cs": "Pokud jste uživatelem programu SLP® od firmy SEKK®, do slp.blue automaticky převedete data včetně číselníků a stávající dokumentace. slp.blue nabízí přehledný a rychlý způsob
můžete automaticky převést všechna data
```suggestion
      "description_cs": "Pokud jste uživatelem programu SLP® od firmy SEKK®, do slp.blue můžete automaticky převést všechna data včetně číselníků a stávající dokumentace. slp.blue nabízí přehledný a rychlý způsob kontroly převedených dokumentů.", 
```

2023-04-13 08:35 UTC, tomaskourim commented on projects/slp.blue.json
> +      "description_en": "All functionalities are available from any device with a web browser without any third-party sotware. The application meets the latest standards of cyber security and data pr
```suggestion
      "description_en": "All functionalities are available from any device with a web browser without any third-party software. The application meets the latest standards of cyber security and data protection."
```

2023-04-13 09:41 UTC, bielovico commented
All suggested changes accepted

2023-04-17 14:24 UTC, tomaskourim approved these changes

2023-04-17 14:32 UTC, merged