Add marketa
mild-blue/about pull request #71
Opened 2021-11-04 18:31 UTC by MildBlueServiceAccount

Nahraný obrázek ve správném formátu.

2021-11-04 18:35 UTC, kubantjan requested changes
Jeste teda je potreba prejmenovat marketa na marketa.json

2021-11-04 18:35 UTC, kubantjan commented on people/sources.json
> +  "marketa"
tady je potreba jeste za tim skalahonza mit carku

2021-11-04 18:37 UTC, kubantjan reviewed
Prvni komentare k textu

2021-11-04 18:37 UTC, kubantjan commented on people/marketa
> +  "short_desc_cs": "Markéta je nejnovější člen našeho týmu. Než přišla k nám, věnovala se financím a couchingu. Práci s lidmi má prostě v krvi. Je to náš happyness manažer, který se stará o tom, aby
happiness

2021-11-04 18:37 UTC, kubantjan commented on people/marketa
> +  "short_desc_en": "Markéta is the newest member of our team. Before she came here, she devoted herself to finances and couching. She simply has work with people in her blood. She is our happyness ma
couching se neda podle me takhle pouzit

2021-11-04 18:43 UTC, kubantjan reviewed
Jinak mi to prijde fajn :)

2021-11-04 18:43 UTC, kubantjan commented on people/marketa.json
> +  "short_desc_de": "Markéta ist das neueste Mitglied unseres Teams. Bevor sie zu uns kam, widmete sie sich den Finanzen und dem Couching. Sie hat einfach die Arbeit mit Menschen im Blut. Sie ist unse
tecka na konci :)

2021-11-04 18:43 UTC, kubantjan commented on people/marketa.json
> +  "short_desc_de": "Markéta ist das neueste Mitglied unseres Teams. Bevor sie zu uns kam, widmete sie sich den Finanzen und dem Couching. Sie hat einfach die Arbeit mit Menschen im Blut. Sie ist unse
jinak mi ta nemcina prijde ok, ale nejsem 100% nemcinar, pak si asi stejne jeste nechame tu stranku na tu nemcinu nekym zkontrolovat

2021-11-04 18:43 UTC, kubantjan commented on people/marketa.json
> +  "short_desc_en": "Markéta is the newest member of our team. Before she came here, she devoted herself to finances and couching. She simply has work with people in her blood. She is our happyness ma
has THE work

2021-11-04 19:01 UTC, kubantjan reviewed
Ještě pár vyjasňovacích k tvé roli.

Komunikace s klienty a dodavateli tím myslíš co? 

Dodavatelé jsi pro nás vlastně i ty ne? (plus ostatní icari jinak vlastně dodavatele nemáme. 

Komunikace s klienty je zatím spíš čistě na nás. To se nějak asi bude vyvíjet, ale možná bych sem spíš dal marketing.

A pak bych za sebe vypichnul že budeš dělat hr :)

A co znamená vlastně ten happiness manager? Řešení kanceláře a teambuildingu? Vlastně to slovo nemám moc definovány.

2021-11-05 08:43 UTC, MildBlueServiceAccount commented on people/sources.json
> +  "marketa"
Doplněno

2021-11-08 12:58 UTC, kubantjan approved these changes

2021-11-08 12:58 UTC, merged