written -> wrote
mild-blue/about pull request #9
Opened 2020-12-02 20:28 UTC by tomaskourim

rozhlas
slogan

Zmena nazvu souboru, asi je to na webu potreba reflektovat, tak prosim nekdy @misslecter :)

2020-12-02 20:36 UTC, kubantjan commented
@tomaskourim  zmena nazvu souboru do budoucna nebude potreba na webu reflektovat. Resi se to v source list filu.

2020-12-02 20:37 UTC, kubantjan requested changes
@tomaskourim  zmena nazvu souboru do budoucna nebude potreba na webu reflektovat. Resi se to v source list filu.

jakmile se mergne ten PR nasti, tak uz muzeme mergnout tenhle beze strachu, ale musis fixnout jeste ten source_list file

2020-12-02 21:03 UTC, tomaskourim commented
> 
> 
> @tomaskourim zmena nazvu souboru do budoucna nebude potreba na webu reflektovat. Resi se to v source list filu.

Spatne jsem se vyjadril. Zmenil jsem nazev slozky. Ta se v source_listu neprojevi. Ale kouknu na web repo a opravim pripadne rovnou i tam.

2020-12-02 21:59 UTC, kubantjan commented
ok approve, mergnul bych az mergneme ten web od nasti

2020-12-04 07:38 UTC, marazt approved these changes

2020-12-05 10:10 UTC, misslecter approved these changes
Ok, pojdme mergnout a já rovnou na webu opravím název složky v url

2020-12-05 10:24 UTC, merged