Add Kristina to web
mild-blue/about pull request #93
Opened 2022-03-01 14:57 UTC by kristinagalik

2022-03-02 22:04 UTC, tomaskourim requested changes
takove pocitove jazykove upravy...

2022-03-02 22:04 UTC, tomaskourim commented on people/kristina.json
> +    "short_desc_de": "Kristina studiert Theoretische Informatik an der University of Glasgow. In der Mild Blue entwickelt sie das Backend und Frontend."
In Mild Blue entwickelt sie Backend sowohl auch Frontend von unseren Apps.

2022-03-02 22:04 UTC, tomaskourim commented on people/kristina.json
> +    "short_desc_en": "Kristina studies theoretical computing science at the University of Glasgow. In Mild Blue, she devotes her time to backend and frontend development.",
she devotes her time to both backend and frontend development

2022-03-02 23:47 UTC, kristinagalik commented
@tomaskourim dakujem, opravene :)

2022-03-03 10:45 UTC, kubantjan commented
Pak davej vzdycky prosim re-request review:
![Screenshot from 2022-03-03 11-43-55](https://user-images.githubusercontent.com/24394374/156549362-f51f0c35-44ad-4023-9c10-de591ed93812.png)

2022-03-03 10:46 UTC, kubantjan approved these changes
Za me dobre :)

2022-03-03 10:58 UTC, merged